### PR TITLE
feat(core): geolocation feature

### PR DESCRIPTION
**Pull request by blakebyrnes**
Add ability to set geolocation for an agent.

### CODE REVIEW

**Comment by janisblaus** [comment]
any chance to get this merged? 😍

**Comment by blakebyrnes** [comment]
> any chance to get this merged? 😍

It's coming soon!! Sorry for the delay. We're wrapping up the plugin architecture as we speak. We can merge this, but it won't do any good until we actually get the plugins resolved so we can push out a new release.

**Comment by janisblaus** [comment]
Hi guys, what could be an approx estimate of merging those changes? I really appreciate your work!!

**Comment by calebjclark** [comment]
@janisblaus, it should be this week. Thanks for your patience!

**Pull request merged**
